package com.example.demo;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class TestinscriptionTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver",
                "C:\\Users\\ESSADIKI Youssef\\Desktop\\demo\\src\\test\\java\\com\\example\\demo\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testinscription() throws InterruptedException {
        driver.get("http://localhost:3000/");
        Thread.sleep(1000);
        driver.manage().window().setSize(new Dimension(889, 669));
        driver.findElement(By.cssSelector("a > .text-white")).click();
        Thread.sleep(1000);
        driver.findElement(By.cssSelector(".form-control:nth-child(4)")).click();
        driver.findElement(By.cssSelector(".form-control:nth-child(4)")).sendKeys("test123");
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("test123");
        driver.findElement(By.cssSelector("#root > div")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).sendKeys("password");
        driver.findElement(By.id("exampleInputEmail1")).click();
        driver.findElement(By.id("exampleInputEmail1")).sendKeys("test123@gmail.com");
        driver.findElement(By.id("exampleInputRole1")).click();
        driver.findElement(By.id("exampleInputRole1")).sendKeys("ADMIN");
        driver.findElement(By.cssSelector(".btn")).click();
        Thread.sleep(1000);
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("test123");
        driver.findElement(By.cssSelector("#root > div")).click();
        driver.findElement(By.id("password")).sendKeys("password");
        driver.findElement(By.cssSelector(".btn")).click();
        Thread.sleep(3000);
//    driver.findElement(By.id("course")).click();

    }

    @Test
    public void testConnectAndCreateNewCourse() throws InterruptedException {
        driver.get("http://localhost:3000/");
        Thread.sleep(2000);
        driver.manage().window().setSize(new Dimension(1552, 880));
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("xenoop");
        driver.findElement(By.id("password")).sendKeys("xenoop");
        driver.findElement(By.cssSelector(".btn")).click();
        Thread.sleep(2000);
        driver.findElement(By.cssSelector("#course > .list-group-item")).click();
        Thread.sleep(1000);

        driver.findElement(By.id("namecourse")).click();
        driver.findElement(By.id("namecourse")).sendKeys("testCourse1");
        driver.findElement(By.id("desccourse")).sendKeys("desc of the course");
        driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control"));
            dropdown.findElement(By.xpath("//option[. = 'retbi asmae Id : 2']")).click();
        }
        driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).click();
        driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
        Thread.sleep(2000);
    }
}
